/*
###############################################################
#  Generated by:      Cadence Encounter 10.13-s089_1
#  OS:                Linux x86_64(Host ID ieng6-ece-03.ucsd.edu)
#  Generated on:      Wed Feb 10 15:14:15 2016
#  Design:            usb_phy
#  Command:           saveNetlist usb_phy.v
###############################################################
*/
/*
###############################################################
#  Generated by:      Cadence Encounter 10.13-s089_1
#  OS:                Linux x86_64(Host ID ieng6-ece-03.ucsd.edu)
#  Generated on:      Wed Feb 10 15:03:00 2016
#  Design:            usb_phy
#  Command:           saveDesign usb_phy_routed.enc
###############################################################
*/
module usb_phy (
	DataOut_i_0_, 
	DataOut_i_1_, 
	DataOut_i_2_, 
	DataOut_i_3_, 
	DataOut_i_4_, 
	DataOut_i_5_, 
	DataOut_i_6_, 
	DataOut_i_7_, 
	TxValid_i, 
	clk, 
	phy_tx_mode, 
	rst, 
	rxd, 
	rxdn, 
	rxdp, 
	DataIn_o_0_, 
	DataIn_o_1_, 
	DataIn_o_2_, 
	DataIn_o_3_, 
	DataIn_o_4_, 
	DataIn_o_5_, 
	DataIn_o_6_, 
	DataIn_o_7_, 
	LineState_o_0_, 
	LineState_o_1_, 
	RxActive_o, 
	RxError_o, 
	RxValid_o, 
	TxReady_o, 
	g1897_u0_o, 
	txdn, 
	txdp, 
	txoe, 
	usb_rst);
   input DataOut_i_0_;
   input DataOut_i_1_;
   input DataOut_i_2_;
   input DataOut_i_3_;
   input DataOut_i_4_;
   input DataOut_i_5_;
   input DataOut_i_6_;
   input DataOut_i_7_;
   input TxValid_i;
   input clk;
   input phy_tx_mode;
   input rst;
   input rxd;
   input rxdn;
   input rxdp;
   output DataIn_o_0_;
   output DataIn_o_1_;
   output DataIn_o_2_;
   output DataIn_o_3_;
   output DataIn_o_4_;
   output DataIn_o_5_;
   output DataIn_o_6_;
   output DataIn_o_7_;
   output LineState_o_0_;
   output LineState_o_1_;
   output RxActive_o;
   output RxError_o;
   output RxValid_o;
   output TxReady_o;
   output g1897_u0_o;
   output txdn;
   output txdp;
   output txoe;
   output usb_rst;

   // Internal wires
   wire FE_PSN9_n243;
   wire FE_PSN8_n243;
   wire FE_PSN7_rst;
   wire FE_PSN6_rst;
   wire FE_PSN5_n247;
   wire FE_PSN4_n247;
   wire FE_OFCN3_n467;
   wire FE_OFCN2_n467;
   wire FE_OFCN1_n266;
   wire FE_OFCN0_n266;
   wire i_rx_phy_rx_en;
   wire i_rx_phy_rxdp_s;
   wire n_459;
   wire n_929;
   wire n_224;
   wire n_885;
   wire n_796;
   wire n_523;
   wire n_417;
   wire n_499;
   wire rst_cnt_3_;
   wire n_428;
   wire n_507;
   wire n_414;
   wire i_rx_phy_bit_cnt_2_;
   wire n_353;
   wire i_rx_phy_sd_nrzi;
   wire n_432;
   wire i_rx_phy_rx_valid_r;
   wire n_388;
   wire n_306;
   wire i_tx_phy_hold_reg;
   wire i_tx_phy_hold_reg_4;
   wire i_tx_phy_hold_reg_5;
   wire i_tx_phy_hold_reg_6;
   wire i_tx_phy_hold_reg_7;
   wire i_tx_phy_hold_reg_8;
   wire i_tx_phy_hold_reg_9;
   wire n_415;
   wire n_427;
   wire i_tx_phy_hold_reg_10;
   wire n_401;
   wire n_449;
   wire n_436;
   wire i_rx_phy_rxdn_s;
   wire n_409;
   wire n_367;
   wire n_407;
   wire n_366;
   wire n_395;
   wire n_394;
   wire n_406;
   wire n_405;
   wire n_378;
   wire n_365;
   wire n_392;
   wire n_364;
   wire rst_cnt_4_;
   wire i_tx_phy_bit_cnt_2_;
   wire n_276;
   wire i_tx_phy_txoe_r1;
   wire n_238;
   wire n_275;
   wire n_362;
   wire n_310;
   wire n_309;
   wire n_338;
   wire i_rx_phy_dpll_state_1_;
   wire n_361;
   wire n_387;
   wire i_tx_phy_sd_nrzi_o;
   wire i_tx_phy_one_cnt_2_;
   wire i_rx_phy_shift_en;
   wire i_rx_phy_rx_valid1;
   wire n_333;
   wire i_tx_phy_bit_cnt_0_;
   wire i_rx_phy_bit_cnt_0_;
   wire i_tx_phy_sd_raw_o;
   wire n_229;
   wire i_tx_phy_data_done;
   wire n_320;
   wire n_319;
   wire n_291;
   wire n_317;
   wire n_316;
   wire n_288;
   wire i_tx_phy_hold_reg_d_14;
   wire i_rx_phy_rxdp_s0;
   wire i_rx_phy_rxdn_s0;
   wire i_tx_phy_hold_reg_d_17;
   wire i_tx_phy_hold_reg_d;
   wire i_rx_phy_rxd_s0;
   wire i_tx_phy_txoe_r2;
   wire i_tx_phy_hold_reg_d_12;
   wire i_tx_phy_sd_bs_o;
   wire i_tx_phy_append_eop_sync2;
   wire n_166;
   wire i_tx_phy_tx_ip;
   wire i_rx_phy_sd_r;
   wire i_tx_phy_append_eop_sync1;
   wire i_tx_phy_append_eop;
   wire i_tx_phy_append_eop_sync4;
   wire n_203;
   wire i_rx_phy_one_cnt_0_;
   wire i_tx_phy_one_cnt_0_;
   wire i_tx_phy_sft_done_r;
   wire i_rx_phy_rxd_r;
   wire i_tx_phy_bit_cnt_1_;
   wire i_rx_phy_dpll_state_0_;
   wire i_rx_phy_one_cnt_1_;
   wire rst_cnt_1_;
   wire i_tx_phy_one_cnt_1_;
   wire i_rx_phy_one_cnt_2_;
   wire rst_cnt_0_;
   wire i_rx_phy_se0_s;
   wire i_rx_phy_rxd_s;
   wire n_758;
   wire n_925;
   wire i_tx_phy_sft_done;
   wire i_rx_phy_fs_state_2_;
   wire i_tx_phy_state_2_;
   wire i_tx_phy_state_1_;
   wire n_962;
   wire n_976;
   wire i_rx_phy_fs_state_0_;
   wire n_992;
   wire i_rx_phy_bit_stuff_err_reg_Q;
   wire i_rx_phy_byte_err_reg_Q;
   wire i_rx_phy_fs_ce_r1;
   wire i_rx_phy_fs_ce_r2;
   wire i_rx_phy_rxd_s1_reg_Q;
   wire i_rx_phy_rxdn_s_r_reg_Q;
   wire i_rx_phy_rxdp_s_r_reg_Q;
   wire i_rx_phy_se0_r_reg_Q;
   wire i_rx_phy_sync_err_reg_Q;
   wire i_tx_phy_hold_reg_d_reg_1__Q;
   wire i_tx_phy_hold_reg_d_reg_3__Q;
   wire i_tx_phy_hold_reg_d_reg_5__Q;
   wire i_tx_phy_hold_reg_d_reg_6__Q;
   wire i_tx_phy_ld_data_reg_Q;
   wire n4;
   wire n12;
   wire n26;
   wire n30;
   wire n47;
   wire n48;
   wire n49;
   wire n50;
   wire n51;
   wire n52;
   wire n53;
   wire n219;
   wire n220;
   wire n221;
   wire n222;
   wire n223;
   wire n224;
   wire n225;
   wire n226;
   wire n227;
   wire n228;
   wire n229;
   wire n230;
   wire n231;
   wire n232;
   wire n233;
   wire n234;
   wire n235;
   wire n236;
   wire n237;
   wire n238;
   wire n239;
   wire n240;
   wire n241;
   wire n242;
   wire n243;
   wire n244;
   wire n245;
   wire n246;
   wire n247;
   wire n248;
   wire n249;
   wire n250;
   wire n251;
   wire n252;
   wire n253;
   wire n254;
   wire n255;
   wire n256;
   wire n257;
   wire n258;
   wire n259;
   wire n260;
   wire n261;
   wire n262;
   wire n263;
   wire n264;
   wire n265;
   wire n266;
   wire n267;
   wire n268;
   wire n269;
   wire n270;
   wire n271;
   wire n272;
   wire n273;
   wire n274;
   wire n275;
   wire n276;
   wire n277;
   wire n278;
   wire n279;
   wire n280;
   wire n281;
   wire n282;
   wire n283;
   wire n284;
   wire n285;
   wire n286;
   wire n287;
   wire n288;
   wire n289;
   wire n290;
   wire n291;
   wire n292;
   wire n293;
   wire n294;
   wire n295;
   wire n296;
   wire n297;
   wire n298;
   wire n299;
   wire n300;
   wire n301;
   wire n302;
   wire n303;
   wire n304;
   wire n305;
   wire n306;
   wire n307;
   wire n308;
   wire n309;
   wire n310;
   wire n311;
   wire n312;
   wire n313;
   wire n314;
   wire n315;
   wire n316;
   wire n317;
   wire n318;
   wire n319;
   wire n320;
   wire n321;
   wire n322;
   wire n323;
   wire n324;
   wire n325;
   wire n326;
   wire n327;
   wire n328;
   wire n329;
   wire n330;
   wire n331;
   wire n332;
   wire n333;
   wire n334;
   wire n335;
   wire n336;
   wire n337;
   wire n338;
   wire n339;
   wire n340;
   wire n341;
   wire n342;
   wire n343;
   wire n344;
   wire n345;
   wire n346;
   wire n347;
   wire n348;
   wire n349;
   wire n350;
   wire n351;
   wire n352;
   wire n353;
   wire n354;
   wire n355;
   wire n356;
   wire n357;
   wire n358;
   wire n359;
   wire n360;
   wire n361;
   wire n362;
   wire n363;
   wire n364;
   wire n365;
   wire n366;
   wire n367;
   wire n368;
   wire n369;
   wire n370;
   wire n371;
   wire n372;
   wire n373;
   wire n374;
   wire n375;
   wire n376;
   wire n377;
   wire n378;
   wire n379;
   wire n380;
   wire n381;
   wire n382;
   wire n383;
   wire n384;
   wire n385;
   wire n386;
   wire n387;
   wire n388;
   wire n389;
   wire n390;
   wire n391;
   wire n392;
   wire n393;
   wire n394;
   wire n395;
   wire n396;
   wire n397;
   wire n398;
   wire n399;
   wire n400;
   wire n401;
   wire n402;
   wire n403;
   wire n404;
   wire n405;
   wire n406;
   wire n407;
   wire n408;
   wire n409;
   wire n410;
   wire n411;
   wire n412;
   wire n413;
   wire n414;
   wire n415;
   wire n416;
   wire n417;
   wire n418;
   wire n419;
   wire n420;
   wire n421;
   wire n422;
   wire n423;
   wire n424;
   wire n425;
   wire n426;
   wire n427;
   wire n428;
   wire n429;
   wire n430;
   wire n431;
   wire n432;
   wire n433;
   wire n434;
   wire n435;
   wire n436;
   wire n437;
   wire n438;
   wire n439;
   wire n440;
   wire n441;
   wire n442;
   wire n443;
   wire n444;
   wire n445;
   wire n446;
   wire n447;
   wire n448;
   wire n449;
   wire n450;
   wire n451;
   wire n452;
   wire n453;
   wire n454;
   wire n455;
   wire n456;
   wire n457;
   wire n458;
   wire n459;
   wire n460;
   wire n461;
   wire n462;
   wire n463;
   wire n464;
   wire n465;
   wire n466;
   wire n467;
   wire n468;
   wire n469;
   wire n470;
   wire n471;
   wire n472;
   wire n473;
   wire n474;
   wire n475;
   wire n476;
   wire n477;
   wire n478;
   wire n479;
   wire n480;
   wire n481;
   wire n482;
   wire n483;
   wire n484;
   wire n485;
   wire n486;
   wire n487;
   wire n488;
   wire n489;
   wire n490;
   wire n491;
   wire n492;
   wire n493;
   wire n494;
   wire n495;
   wire n496;
   wire n497;
   wire n498;
   wire n499;
   wire n500;
   wire n501;
   wire n502;
   wire n503;
   wire n504;
   wire n505;
   wire n506;
   wire n507;
   wire n508;
   wire n509;
   wire n510;
   wire n511;
   wire n512;

   in01f03 FE_PSC9_n243 (.o(FE_PSN9_n243), 
	.a(n243));
   in01f03 FE_PSC8_n243 (.o(FE_PSN8_n243), 
	.a(FE_PSN9_n243));
   in01f03 FE_PSC7_rst (.o(FE_PSN7_rst), 
	.a(rst));
   in01f08 FE_PSC6_rst (.o(FE_PSN6_rst), 
	.a(FE_PSN7_rst));
   in01f04 FE_PSC5_n247 (.o(FE_PSN5_n247), 
	.a(FE_PSN4_n247));
   in01f04 FE_PSC4_n247 (.o(FE_PSN4_n247), 
	.a(n247));
   in01f10 FE_OFCC3_n467 (.o(FE_OFCN3_n467), 
	.a(FE_OFCN2_n467));
   in01f08 FE_OFCC2_n467 (.o(FE_OFCN2_n467), 
	.a(n467));
   in01f04 FE_OFCC1_n266 (.o(FE_OFCN1_n266), 
	.a(FE_OFCN0_n266));
   in01f02 FE_OFCC0_n266 (.o(FE_OFCN0_n266), 
	.a(n266));
   ms00f80 i_rx_phy_bit_cnt_reg_0__u0 (.o(i_rx_phy_bit_cnt_0_), 
	.d(n_407), 
	.ck(clk));
   ms00f80 i_rx_phy_bit_cnt_reg_1__u0 (.o(n_353), 
	.d(n_405), 
	.ck(clk));
   ms00f80 i_rx_phy_bit_cnt_reg_2__u0 (.o(i_rx_phy_bit_cnt_2_), 
	.d(n_414), 
	.ck(clk));
   ms00f80 i_rx_phy_bit_stuff_err_reg_u0 (.o(i_rx_phy_bit_stuff_err_reg_Q), 
	.d(n220), 
	.ck(clk));
   ms00f80 i_rx_phy_byte_err_reg_u0 (.o(i_rx_phy_byte_err_reg_Q), 
	.d(n_499), 
	.ck(clk));
   ms00f80 i_rx_phy_dpll_state_reg_0__u0 (.o(i_rx_phy_dpll_state_0_), 
	.d(n_449), 
	.ck(clk));
   ms00f80 i_rx_phy_dpll_state_reg_1__u0 (.o(i_rx_phy_dpll_state_1_), 
	.d(n_436), 
	.ck(clk));
   ms00f80 i_rx_phy_fs_ce_r1_reg_u0 (.o(i_rx_phy_fs_ce_r1), 
	.d(n511), 
	.ck(clk));
   ms00f80 i_rx_phy_fs_ce_r2_reg_u0 (.o(i_rx_phy_fs_ce_r2), 
	.d(i_rx_phy_fs_ce_r1), 
	.ck(clk));
   ms00f80 i_rx_phy_fs_ce_reg_u0 (.o(n_885), 
	.d(i_rx_phy_fs_ce_r2), 
	.ck(clk));
   ms00f80 i_rx_phy_fs_state_reg_0__u0 (.o(i_rx_phy_fs_state_0_), 
	.d(n221), 
	.ck(clk));
   ms00f80 i_rx_phy_fs_state_reg_1__u0 (.o(n_796), 
	.d(n_523), 
	.ck(clk));
   ms00f80 i_rx_phy_fs_state_reg_2__u0 (.o(i_rx_phy_fs_state_2_), 
	.d(n_758), 
	.ck(clk));
   ms00f80 i_rx_phy_hold_reg_reg_0__u0 (.o(DataIn_o_0_), 
	.d(DataIn_o_1_), 
	.ck(clk));
   ms00f80 i_rx_phy_hold_reg_reg_1__u0 (.o(DataIn_o_1_), 
	.d(DataIn_o_2_), 
	.ck(clk));
   ms00f80 i_rx_phy_hold_reg_reg_2__u0 (.o(DataIn_o_2_), 
	.d(DataIn_o_3_), 
	.ck(clk));
   ms00f80 i_rx_phy_hold_reg_reg_3__u0 (.o(DataIn_o_3_), 
	.d(DataIn_o_4_), 
	.ck(clk));
   ms00f80 i_rx_phy_hold_reg_reg_4__u0 (.o(DataIn_o_4_), 
	.d(DataIn_o_5_), 
	.ck(clk));
   ms00f80 i_rx_phy_hold_reg_reg_5__u0 (.o(DataIn_o_5_), 
	.d(DataIn_o_6_), 
	.ck(clk));
   ms00f80 i_rx_phy_hold_reg_reg_6__u0 (.o(DataIn_o_6_), 
	.d(DataIn_o_7_), 
	.ck(clk));
   ms00f80 i_rx_phy_hold_reg_reg_7__u0 (.o(DataIn_o_7_), 
	.d(i_rx_phy_sd_nrzi), 
	.ck(clk));
   ms00f80 i_rx_phy_one_cnt_reg_0__u0 (.o(i_rx_phy_one_cnt_0_), 
	.d(n_406), 
	.ck(clk));
   ms00f80 i_rx_phy_one_cnt_reg_1__u0 (.o(i_rx_phy_one_cnt_1_), 
	.d(n_427), 
	.ck(clk));
   ms00f80 i_rx_phy_one_cnt_reg_2__u0 (.o(i_rx_phy_one_cnt_2_), 
	.d(n_962), 
	.ck(clk));
   ms00f80 i_rx_phy_rx_active_reg_u0 (.o(RxActive_o), 
	.d(n509), 
	.ck(clk));
   ms00f80 i_rx_phy_rx_en_reg_u0 (.o(i_rx_phy_rx_en), 
	.d(txoe), 
	.ck(clk));
   ms00f80 i_rx_phy_rx_valid1_reg_u0 (.o(i_rx_phy_rx_valid1), 
	.d(n507), 
	.ck(clk));
   ms00f80 i_rx_phy_rx_valid_r_reg_u0 (.o(i_rx_phy_rx_valid_r), 
	.d(n12), 
	.ck(clk));
   ms00f80 i_rx_phy_rx_valid_reg_u0 (.o(RxValid_o), 
	.d(n222), 
	.ck(clk));
   ms00f80 i_rx_phy_rxd_r_reg_u0 (.o(i_rx_phy_rxd_r), 
	.d(i_rx_phy_rxd_s), 
	.ck(clk));
   ms00f80 i_rx_phy_rxd_s0_reg_u0 (.o(i_rx_phy_rxd_s0), 
	.d(rxd), 
	.ck(clk));
   ms00f80 i_rx_phy_rxd_s1_reg_u0 (.o(i_rx_phy_rxd_s1_reg_Q), 
	.d(i_rx_phy_rxd_s0), 
	.ck(clk));
   ms00f80 i_rx_phy_rxd_s_reg_u0 (.o(i_rx_phy_rxd_s), 
	.d(n_229), 
	.ck(clk));
   ms00f80 i_rx_phy_rxdn_s0_reg_u0 (.o(i_rx_phy_rxdn_s0), 
	.d(rxdn), 
	.ck(clk));
   ms00f80 i_rx_phy_rxdn_s1_reg_u0 (.o(LineState_o_1_), 
	.d(i_rx_phy_rxdn_s0), 
	.ck(clk));
   ms00f80 i_rx_phy_rxdn_s_r_reg_u0 (.o(i_rx_phy_rxdn_s_r_reg_Q), 
	.d(n26), 
	.ck(clk));
   ms00f80 i_rx_phy_rxdn_s_reg_u0 (.o(i_rx_phy_rxdn_s), 
	.d(n_310), 
	.ck(clk));
   ms00f80 i_rx_phy_rxdp_s0_reg_u0 (.o(i_rx_phy_rxdp_s0), 
	.d(rxdp), 
	.ck(clk));
   ms00f80 i_rx_phy_rxdp_s1_reg_u0 (.o(LineState_o_0_), 
	.d(i_rx_phy_rxdp_s0), 
	.ck(clk));
   ms00f80 i_rx_phy_rxdp_s_r_reg_u0 (.o(i_rx_phy_rxdp_s_r_reg_Q), 
	.d(n30), 
	.ck(clk));
   ms00f80 i_rx_phy_rxdp_s_reg_u0 (.o(i_rx_phy_rxdp_s), 
	.d(n_309), 
	.ck(clk));
   ms00f80 i_rx_phy_sd_nrzi_reg_u0 (.o(i_rx_phy_sd_nrzi), 
	.d(n_365), 
	.ck(clk));
   ms00f80 i_rx_phy_sd_r_reg_u0 (.o(i_rx_phy_sd_r), 
	.d(n_203), 
	.ck(clk));
   ms00f80 i_rx_phy_se0_r_reg_u0 (.o(i_rx_phy_se0_r_reg_Q), 
	.d(n510), 
	.ck(clk));
   ms00f80 i_rx_phy_se0_s_reg_u0 (.o(i_rx_phy_se0_s), 
	.d(n4), 
	.ck(clk));
   ms00f80 i_rx_phy_shift_en_reg_u0 (.o(i_rx_phy_shift_en), 
	.d(n_992), 
	.ck(clk));
   ms00f80 i_rx_phy_sync_err_reg_u0 (.o(i_rx_phy_sync_err_reg_Q), 
	.d(n_925), 
	.ck(clk));
   ms00f80 i_tx_phy_TxReady_o_reg_u0 (.o(TxReady_o), 
	.d(n_392), 
	.ck(clk));
   ms00f80 i_tx_phy_append_eop_reg_u0 (.o(i_tx_phy_append_eop), 
	.d(n_409), 
	.ck(clk));
   ms00f80 i_tx_phy_append_eop_sync1_reg_u0 (.o(i_tx_phy_append_eop_sync1), 
	.d(n_317), 
	.ck(clk));
   ms00f80 i_tx_phy_append_eop_sync2_reg_u0 (.o(i_tx_phy_append_eop_sync2), 
	.d(n_316), 
	.ck(clk));
   ms00f80 i_tx_phy_append_eop_sync3_reg_u0 (.o(n_224), 
	.d(n_338), 
	.ck(clk));
   ms00f80 i_tx_phy_append_eop_sync4_reg_u0 (.o(i_tx_phy_append_eop_sync4), 
	.d(n_288), 
	.ck(clk));
   ms00f80 i_tx_phy_bit_cnt_reg_0__u0 (.o(i_tx_phy_bit_cnt_0_), 
	.d(n_395), 
	.ck(clk));
   ms00f80 i_tx_phy_bit_cnt_reg_1__u0 (.o(i_tx_phy_bit_cnt_1_), 
	.d(n_394), 
	.ck(clk));
   ms00f80 i_tx_phy_bit_cnt_reg_2__u0 (.o(i_tx_phy_bit_cnt_2_), 
	.d(n_415), 
	.ck(clk));
   ms00f80 i_tx_phy_data_done_reg_u0 (.o(i_tx_phy_data_done), 
	.d(n_166), 
	.ck(clk));
   ms00f80 i_tx_phy_hold_reg_d_reg_0__u0 (.o(i_tx_phy_hold_reg_d), 
	.d(i_tx_phy_hold_reg), 
	.ck(clk));
   ms00f80 i_tx_phy_hold_reg_d_reg_1__u0 (.o(i_tx_phy_hold_reg_d_reg_1__Q), 
	.d(i_tx_phy_hold_reg_4), 
	.ck(clk));
   ms00f80 i_tx_phy_hold_reg_d_reg_2__u0 (.o(i_tx_phy_hold_reg_d_12), 
	.d(i_tx_phy_hold_reg_5), 
	.ck(clk));
   ms00f80 i_tx_phy_hold_reg_d_reg_3__u0 (.o(i_tx_phy_hold_reg_d_reg_3__Q), 
	.d(i_tx_phy_hold_reg_6), 
	.ck(clk));
   ms00f80 i_tx_phy_hold_reg_d_reg_4__u0 (.o(i_tx_phy_hold_reg_d_14), 
	.d(i_tx_phy_hold_reg_7), 
	.ck(clk));
   ms00f80 i_tx_phy_hold_reg_d_reg_5__u0 (.o(i_tx_phy_hold_reg_d_reg_5__Q), 
	.d(i_tx_phy_hold_reg_8), 
	.ck(clk));
   ms00f80 i_tx_phy_hold_reg_d_reg_6__u0 (.o(i_tx_phy_hold_reg_d_reg_6__Q), 
	.d(i_tx_phy_hold_reg_9), 
	.ck(clk));
   ms00f80 i_tx_phy_hold_reg_d_reg_7__u0 (.o(i_tx_phy_hold_reg_d_17), 
	.d(i_tx_phy_hold_reg_10), 
	.ck(clk));
   ms00f80 i_tx_phy_hold_reg_reg_0__u0 (.o(i_tx_phy_hold_reg), 
	.d(n47), 
	.ck(clk));
   ms00f80 i_tx_phy_hold_reg_reg_1__u0 (.o(i_tx_phy_hold_reg_4), 
	.d(n48), 
	.ck(clk));
   ms00f80 i_tx_phy_hold_reg_reg_2__u0 (.o(i_tx_phy_hold_reg_5), 
	.d(n49), 
	.ck(clk));
   ms00f80 i_tx_phy_hold_reg_reg_3__u0 (.o(i_tx_phy_hold_reg_6), 
	.d(n50), 
	.ck(clk));
   ms00f80 i_tx_phy_hold_reg_reg_4__u0 (.o(i_tx_phy_hold_reg_7), 
	.d(n51), 
	.ck(clk));
   ms00f80 i_tx_phy_hold_reg_reg_5__u0 (.o(i_tx_phy_hold_reg_8), 
	.d(n52), 
	.ck(clk));
   ms00f80 i_tx_phy_hold_reg_reg_6__u0 (.o(i_tx_phy_hold_reg_9), 
	.d(n53), 
	.ck(clk));
   ms00f80 i_tx_phy_hold_reg_reg_7__u0 (.o(i_tx_phy_hold_reg_10), 
	.d(n_507), 
	.ck(clk));
   ms00f80 i_tx_phy_ld_data_reg_u0 (.o(i_tx_phy_ld_data_reg_Q), 
	.d(n_387), 
	.ck(clk));
   ms00f80 i_tx_phy_one_cnt_reg_0__u0 (.o(i_tx_phy_one_cnt_0_), 
	.d(n_378), 
	.ck(clk));
   ms00f80 i_tx_phy_one_cnt_reg_1__u0 (.o(i_tx_phy_one_cnt_1_), 
	.d(n_401), 
	.ck(clk));
   ms00f80 i_tx_phy_one_cnt_reg_2__u0 (.o(i_tx_phy_one_cnt_2_), 
	.d(n_388), 
	.ck(clk));
   ms00f80 i_tx_phy_sd_bs_o_reg_u0 (.o(i_tx_phy_sd_bs_o), 
	.d(n_361), 
	.ck(clk));
   ms00f80 i_tx_phy_sd_nrzi_o_reg_u0 (.o(i_tx_phy_sd_nrzi_o), 
	.d(n_276), 
	.ck(clk));
   ms00f80 i_tx_phy_sd_raw_o_reg_u0 (.o(i_tx_phy_sd_raw_o), 
	.d(n508), 
	.ck(clk));
   ms00f80 i_tx_phy_sft_done_r_reg_u0 (.o(i_tx_phy_sft_done_r), 
	.d(i_tx_phy_sft_done), 
	.ck(clk));
   ms00f80 i_tx_phy_sft_done_reg_u0 (.o(i_tx_phy_sft_done), 
	.d(n224), 
	.ck(clk));
   ms00f80 i_tx_phy_state_reg_0__u0 (.o(n_929), 
	.d(n_459), 
	.ck(clk));
   ms00f80 i_tx_phy_state_reg_1__u0 (.o(i_tx_phy_state_1_), 
	.d(n223), 
	.ck(clk));
   ms00f80 i_tx_phy_state_reg_2__u0 (.o(i_tx_phy_state_2_), 
	.d(n_432), 
	.ck(clk));
   ms00f80 i_tx_phy_tx_ip_reg_u0 (.o(i_tx_phy_tx_ip), 
	.d(n_976), 
	.ck(clk));
   ms00f80 i_tx_phy_tx_ip_sync_reg_u0 (.o(n_238), 
	.d(n_319), 
	.ck(clk));
   ms00f80 i_tx_phy_txdn_reg_u0 (.o(txdn), 
	.d(n_364), 
	.ck(clk));
   ms00f80 i_tx_phy_txdp_reg_u0 (.o(txdp), 
	.d(n_366), 
	.ck(clk));
   ms00f80 i_tx_phy_txoe_r1_reg_u0 (.o(i_tx_phy_txoe_r1), 
	.d(n_320), 
	.ck(clk));
   ms00f80 i_tx_phy_txoe_r2_reg_u0 (.o(i_tx_phy_txoe_r2), 
	.d(n_291), 
	.ck(clk));
   ms00f80 i_tx_phy_txoe_reg_u0 (.o(txoe), 
	.d(n_333), 
	.ck(clk));
   ms00f80 rst_cnt_reg_0__u0 (.o(rst_cnt_0_), 
	.d(n_362), 
	.ck(clk));
   ms00f80 rst_cnt_reg_1__u0 (.o(rst_cnt_1_), 
	.d(n_367), 
	.ck(clk));
   ms00f80 rst_cnt_reg_2__u0 (.o(n_306), 
	.d(n_428), 
	.ck(clk));
   ms00f80 rst_cnt_reg_3__u0 (.o(rst_cnt_3_), 
	.d(n_417), 
	.ck(clk));
   ms00f80 rst_cnt_reg_4__u0 (.o(rst_cnt_4_), 
	.d(n219), 
	.ck(clk));
   ms00f80 usb_rst_reg_u0 (.o(usb_rst), 
	.d(n_275), 
	.ck(clk));
   in01s02 U279 (.o(n387), 
	.a(n_306));
   in01m06 U280 (.o(n310), 
	.a(i_tx_phy_bit_cnt_1_));
   in01s20 U281 (.o(n320), 
	.a(i_tx_phy_bit_cnt_2_));
   na02m20 U282 (.o(n362), 
	.b(n_238), 
	.a(FE_PSN6_rst));
   in01s10 U283 (.o(n297), 
	.a(n_238));
   na02s01 U284 (.o(n314), 
	.b(n313), 
	.a(n320));
   na02s03 U285 (.o(n313), 
	.b(i_tx_phy_bit_cnt_0_), 
	.a(n_885));
   in01m03 U286 (.o(n296), 
	.a(i_tx_phy_bit_cnt_0_));
   no03s04 U287 (.o(n312), 
	.c(n311), 
	.b(i_tx_phy_bit_cnt_2_), 
	.a(i_tx_phy_one_cnt_0_));
   na02s40 U288 (.o(n311), 
	.b(i_tx_phy_one_cnt_2_), 
	.a(i_tx_phy_one_cnt_1_));
   in01s01 U289 (.o(n315), 
	.a(n312));
   in01m20 U290 (.o(n309), 
	.a(i_tx_phy_one_cnt_0_));
   in01s02 U291 (.o(n255), 
	.a(i_tx_phy_one_cnt_1_));
   in01s02 U292 (.o(n254), 
	.a(i_tx_phy_one_cnt_2_));
   na02s01 U293 (.o(n236), 
	.b(DataOut_i_5_), 
	.a(i_tx_phy_ld_data_reg_Q));
   in01s02 U294 (.o(n276), 
	.a(i_tx_phy_ld_data_reg_Q));
   in01s06 U295 (.o(n232), 
	.a(i_rx_phy_bit_cnt_0_));
   na02s20 U296 (.o(n457), 
	.b(i_rx_phy_shift_en), 
	.a(rst));
   na02s03 U297 (.o(n451), 
	.b(i_rx_phy_bit_cnt_0_), 
	.a(n_885));
   in01s20 U298 (.o(n244), 
	.a(i_rx_phy_one_cnt_2_));
   in01s10 U299 (.o(n233), 
	.a(i_rx_phy_one_cnt_1_));
   in01s06 U300 (.o(n449), 
	.a(i_rx_phy_one_cnt_0_));
   in01s10 U301 (.o(n441), 
	.a(n457));
   no03m03 U302 (.o(n_405), 
	.c(n457), 
	.b(n456), 
	.a(n246));
   no02s02 U303 (.o(n456), 
	.b(n455), 
	.a(n_353));
   in01s02 U304 (.o(n490), 
	.a(n488));
   no02s02 U305 (.o(n488), 
	.b(n510), 
	.a(n479));
   in01s08 U306 (.o(n479), 
	.a(n_885));
   no04s02 U307 (.o(n_499), 
	.d(n491), 
	.c(n492), 
	.b(i_rx_phy_se0_r_reg_Q), 
	.a(n493));
   in01s02 U308 (.o(n493), 
	.a(n510));
   no02s04 U309 (.o(n510), 
	.b(i_rx_phy_rxdp_s), 
	.a(i_rx_phy_rxdn_s));
   no02s01 U310 (.o(n491), 
	.b(n_353), 
	.a(i_rx_phy_bit_cnt_2_));
   oa12s02 U311 (.o(n375), 
	.c(i_rx_phy_rxd_r), 
	.b(i_rx_phy_rxd_s), 
	.a(i_rx_phy_rx_en));
   in01m20 U312 (.o(n370), 
	.a(i_rx_phy_dpll_state_0_));
   no02s02 U313 (.o(n_436), 
	.b(n377), 
	.a(FE_OFCN3_n467));
   in01s01 U314 (.o(n376), 
	.a(n226));
   no02m10 U315 (.o(n511), 
	.b(i_rx_phy_dpll_state_1_), 
	.a(n370));
   in01m03 U316 (.o(n371), 
	.a(n511));
   no03m02 U317 (.o(n221), 
	.c(FE_OFCN3_n467), 
	.b(n468), 
	.a(n474));
   no03m04 U318 (.o(n474), 
	.c(n425), 
	.b(n426), 
	.a(n427));
   no02f01 U319 (.o(n468), 
	.b(i_rx_phy_fs_state_0_), 
	.a(n478));
   in01s02 U320 (.o(n494), 
	.a(n_796));
   na02s01 U321 (.o(n428), 
	.b(n_796), 
	.a(rst));
   oa12f01 U322 (.o(n_758), 
	.c(n474), 
	.b(n475), 
	.a(n473));
   na02s03 U323 (.o(n475), 
	.b(i_rx_phy_fs_state_2_), 
	.a(rst));
   oa22s02 U324 (.o(n_406), 
	.d(n442), 
	.c(n457), 
	.b(n457), 
	.a(n234));
   na02s01 U325 (.o(n234), 
	.b(n440), 
	.a(n450));
   na02s01 U326 (.o(n442), 
	.b(i_rx_phy_one_cnt_0_), 
	.a(n479));
   oa22m01 U327 (.o(n_427), 
	.d(n447), 
	.c(n448), 
	.b(n445), 
	.a(n446));
   no03m02 U328 (.o(n444), 
	.c(n489), 
	.b(n457), 
	.a(i_rx_phy_one_cnt_1_));
   na02s01 U329 (.o(n439), 
	.b(i_rx_phy_one_cnt_2_), 
	.a(n443));
   na03s04 U330 (.o(n438), 
	.c(n437), 
	.b(n441), 
	.a(i_rx_phy_sd_nrzi));
   na02s10 U331 (.o(n392), 
	.b(n_306), 
	.a(rst_cnt_1_));
   na02s02 U332 (.o(n417), 
	.b(phy_tx_mode), 
	.a(n227));
   in01s10 U333 (.o(n499), 
	.a(i_rx_phy_rx_en));
   in01s01 U334 (.o(n230), 
	.a(i_rx_phy_shift_en));
   ao12s02 U335 (.o(n359), 
	.c(n227), 
	.b(i_tx_phy_tx_ip), 
	.a(n358));
   in01s01 U336 (.o(n407), 
	.a(n307));
   no03s02 U337 (.o(n318), 
	.c(n313), 
	.b(n310), 
	.a(n406));
   na02s02 U338 (.o(n504), 
	.b(n501), 
	.a(n502));
   oa12s02 U339 (.o(n248), 
	.c(i_rx_phy_rxd_s1_reg_Q), 
	.b(i_rx_phy_rxd_s0), 
	.a(i_rx_phy_rxd_s));
   no03s01 U340 (.o(n506), 
	.c(i_rx_phy_bit_stuff_err_reg_Q), 
	.b(i_rx_phy_byte_err_reg_Q), 
	.a(i_rx_phy_sync_err_reg_Q));
   no03s04 U341 (.o(n_275), 
	.c(n403), 
	.b(n404), 
	.a(n405));
   oa12s04 U342 (.o(n48), 
	.c(n288), 
	.b(n289), 
	.a(n287));
   in01s02 U343 (.o(n388), 
	.a(rst_cnt_3_));
   na02s02 U344 (.o(n293), 
	.b(i_tx_phy_hold_reg_d), 
	.a(n296));
   na02s08 U345 (.o(n352), 
	.b(n482), 
	.a(n332));
   no04s04 U346 (.o(n354), 
	.d(n228), 
	.c(n350), 
	.b(n_224), 
	.a(n351));
   ao12s02 U347 (.o(n316), 
	.c(n320), 
	.b(n310), 
	.a(n362));
   no02s04 U348 (.o(n478), 
	.b(n425), 
	.a(n426));
   na02m04 U349 (.o(n397), 
	.b(n384), 
	.a(n385));
   na02s01 U350 (.o(n422), 
	.b(i_rx_phy_rxdn_s0), 
	.a(LineState_o_1_));
   na02f04 U351 (.o(n351), 
	.b(n482), 
	.a(n245));
   in01f01 U352 (.o(n305), 
	.a(n302));
   in01f08 U353 (.o(n228), 
	.a(n_885));
   na02s03 U354 (.o(n445), 
	.b(i_rx_phy_one_cnt_0_), 
	.a(n_885));
   na02f02 U355 (.o(n225), 
	.b(n262), 
	.a(i_tx_phy_state_1_));
   na02s03 U356 (.o(n329), 
	.b(n262), 
	.a(i_tx_phy_state_1_));
   in01f02 U357 (.o(n337), 
	.a(n350));
   in01f10 U358 (.o(n489), 
	.a(i_rx_phy_sd_nrzi));
   na03f03 U359 (.o(n317), 
	.c(n314), 
	.b(n315), 
	.a(n316));
   na02f04 U360 (.o(n289), 
	.b(n276), 
	.a(n265));
   na02s03 U361 (.o(n226), 
	.b(i_rx_phy_dpll_state_1_), 
	.a(n370));
   no02f02 U362 (.o(n_976), 
	.b(n359), 
	.a(FE_OFCN3_n467));
   na02f10 U363 (.o(n425), 
	.b(n_885), 
	.a(n239));
   ao22f02 U364 (.o(n328), 
	.d(FE_PSN8_n243), 
	.c(i_tx_phy_append_eop_sync2), 
	.b(n_224), 
	.a(n327));
   no02f04 U365 (.o(n243), 
	.b(FE_OFCN3_n467), 
	.a(n479));
   no02s08 U366 (.o(n384), 
	.b(usb_rst), 
	.a(n228));
   no03s20 U367 (.o(n453), 
	.c(n233), 
	.b(n244), 
	.a(i_rx_phy_one_cnt_0_));
   na02f08 U368 (.o(n405), 
	.b(rst_cnt_1_), 
	.a(rst_cnt_0_));
   na02s03 U369 (.o(n360), 
	.b(n413), 
	.a(n479));
   in01s06 U370 (.o(n413), 
	.a(n362));
   in01s20 U371 (.o(n341), 
	.a(i_tx_phy_sft_done));
   na02s03 U372 (.o(n350), 
	.b(i_tx_phy_state_2_), 
	.a(rst));
   in01s08 U373 (.o(n496), 
	.a(i_rx_phy_fs_state_0_));
   oa12s10 U374 (.o(n426), 
	.c(i_rx_phy_rxdp_s), 
	.b(i_rx_phy_rxdn_s), 
	.a(n492));
   na02f02 U375 (.o(n404), 
	.b(rst_cnt_3_), 
	.a(n_306));
   in01s04 U376 (.o(n403), 
	.a(rst_cnt_4_));
   in01s01 U377 (.o(n385), 
	.a(n405));
   no03m04 U378 (.o(n398), 
	.c(FE_OFCN3_n467), 
	.b(LineState_o_1_), 
	.a(LineState_o_0_));
   no02m04 U379 (.o(n391), 
	.b(usb_rst), 
	.a(n378));
   in01f06 U380 (.o(n332), 
	.a(i_tx_phy_state_2_));
   no02s10 U381 (.o(n345), 
	.b(i_tx_phy_sft_done_r), 
	.a(n341));
   na02s03 U382 (.o(n292), 
	.b(i_tx_phy_hold_reg_d_reg_1__Q), 
	.a(i_tx_phy_bit_cnt_0_));
   no03s03 U383 (.o(n295), 
	.c(n290), 
	.b(n310), 
	.a(n297));
   oa12s10 U384 (.o(n290), 
	.c(i_tx_phy_hold_reg_d_12), 
	.b(i_tx_phy_bit_cnt_0_), 
	.a(n320));
   na02s03 U385 (.o(n319), 
	.b(i_tx_phy_bit_cnt_1_), 
	.a(i_tx_phy_bit_cnt_0_));
   in01s02 U386 (.o(n303), 
	.a(n319));
   no02s10 U387 (.o(n406), 
	.b(i_tx_phy_one_cnt_0_), 
	.a(n311));
   no02s03 U388 (.o(n483), 
	.b(n245), 
	.a(n352));
   no03m04 U389 (.o(n463), 
	.c(n499), 
	.b(FE_OFCN3_n467), 
	.a(i_rx_phy_rxdp_s));
   na02s03 U390 (.o(n436), 
	.b(i_rx_phy_one_cnt_1_), 
	.a(n244));
   in01s40 U391 (.o(n498), 
	.a(i_rx_phy_fs_state_2_));
   in01s20 U392 (.o(n239), 
	.a(i_rx_phy_se0_s));
   no04m03 U393 (.o(n472), 
	.d(FE_OFCN3_n467), 
	.c(n499), 
	.b(i_rx_phy_rxdn_s), 
	.a(n496));
   in01s01 U394 (.o(n503), 
	.a(n478));
   no03f02 U395 (.o(n427), 
	.c(n499), 
	.b(i_rx_phy_fs_state_0_), 
	.a(i_rx_phy_rxdp_s));
   na02s03 U396 (.o(n373), 
	.b(i_rx_phy_dpll_state_1_), 
	.a(n370));
   na02f04 U397 (.o(n372), 
	.b(i_rx_phy_rxd_s), 
	.a(i_rx_phy_rxd_r));
   no02m04 U398 (.o(n246), 
	.b(n453), 
	.a(n454));
   in01s04 U399 (.o(n361), 
	.a(i_tx_phy_tx_ip));
   ao12s04 U400 (.o(n_166), 
	.c(n339), 
	.b(i_tx_phy_tx_ip), 
	.a(n512));
   in01s04 U401 (.o(n321), 
	.a(i_tx_phy_append_eop_sync4));
   oa22s04 U402 (.o(n435), 
	.d(i_rx_phy_sd_r), 
	.c(n430), 
	.b(i_rx_phy_rxd_s), 
	.a(n431));
   ao22m02 U403 (.o(n433), 
	.d(i_rx_phy_sd_nrzi), 
	.c(n432), 
	.b(rst), 
	.a(n492));
   in01s04 U404 (.o(n12), 
	.a(n462));
   no02s04 U405 (.o(n298), 
	.b(n297), 
	.a(n320));
   no02s01 U406 (.o(n389), 
	.b(n388), 
	.a(n392));
   in01s04 U407 (.o(n364), 
	.a(i_tx_phy_txoe_r1));
   no02s03 U408 (.o(n336), 
	.b(i_tx_phy_state_1_), 
	.a(n_885));
   na02s03 U409 (.o(n333), 
	.b(i_tx_phy_state_1_), 
	.a(n332));
   ao12s08 U410 (.o(n342), 
	.c(i_tx_phy_state_1_), 
	.b(n_224), 
	.a(n245));
   no02s03 U411 (.o(n343), 
	.b(i_tx_phy_state_2_), 
	.a(FE_OFCN3_n467));
   no03m03 U412 (.o(n348), 
	.c(n340), 
	.b(i_tx_phy_state_2_), 
	.a(i_tx_phy_sft_done_r));
   na02s03 U413 (.o(n340), 
	.b(i_tx_phy_state_1_), 
	.a(n339));
   no03m03 U414 (.o(n347), 
	.c(FE_OFCN3_n467), 
	.b(n341), 
	.a(n_929));
   na02s03 U415 (.o(n256), 
	.b(i_tx_phy_sd_raw_o), 
	.a(n309));
   no02s03 U416 (.o(n358), 
	.b(n352), 
	.a(n277));
   no04m08 U417 (.o(n237), 
	.d(i_tx_phy_state_1_), 
	.c(n_929), 
	.b(n266), 
	.a(i_tx_phy_state_2_));
   no02s08 U418 (.o(n267), 
	.b(n_929), 
	.a(FE_OFCN1_n266));
   no02s08 U419 (.o(n268), 
	.b(i_tx_phy_state_1_), 
	.a(i_tx_phy_state_2_));
   in01s04 U420 (.o(n339), 
	.a(i_tx_phy_data_done));
   in01s06 U421 (.o(n227), 
	.a(n_224));
   ao12s04 U422 (.o(n501), 
	.c(i_rx_phy_fs_state_2_), 
	.b(n_796), 
	.a(n500));
   no03s10 U423 (.o(n500), 
	.c(n498), 
	.b(n499), 
	.a(i_rx_phy_rxdp_s));
   ao12s04 U424 (.o(n502), 
	.c(n497), 
	.b(i_rx_phy_rx_en), 
	.a(n496));
   in01s04 U425 (.o(n497), 
	.a(i_rx_phy_rxdn_s));
   in01s04 U426 (.o(n430), 
	.a(i_rx_phy_rxd_s));
   in01s04 U427 (.o(n431), 
	.a(i_rx_phy_sd_r));
   na02s03 U428 (.o(n469), 
	.b(n_796), 
	.a(n498));
   no02s03 U429 (.o(n471), 
	.b(n510), 
	.a(RxActive_o));
   in01s03 U430 (.o(n467), 
	.a(rst));
   in01m20 U431 (.o(n492), 
	.a(RxActive_o));
   oa12s04 U432 (.o(n400), 
	.c(n399), 
	.b(rst_cnt_4_), 
	.a(n398));
   no02m02 U433 (.o(n383), 
	.b(n391), 
	.a(rst_cnt_1_));
   no03m03 U434 (.o(n_362), 
	.c(n382), 
	.b(n380), 
	.a(n391));
   ao12s04 U435 (.o(n380), 
	.c(n379), 
	.b(n_885), 
	.a(rst_cnt_0_));
   in01s04 U436 (.o(n379), 
	.a(usb_rst));
   na02m02 U437 (.o(n_333), 
	.b(rst), 
	.a(n366));
   oa12s04 U438 (.o(n366), 
	.c(txoe), 
	.b(n_885), 
	.a(n365));
   oa12s04 U439 (.o(n365), 
	.c(i_tx_phy_txoe_r2), 
	.b(i_tx_phy_txoe_r1), 
	.a(n_885));
   oa22s04 U440 (.o(n_291), 
	.d(FE_PSN5_n247), 
	.c(n363), 
	.b(n364), 
	.a(n434));
   in01s04 U441 (.o(n363), 
	.a(i_tx_phy_txoe_r2));
   oa22s04 U442 (.o(n_320), 
	.d(n479), 
	.c(n362), 
	.b(FE_PSN5_n247), 
	.a(n364));
   na02s03 U443 (.o(n_366), 
	.b(rst), 
	.a(n416));
   oa22s04 U444 (.o(n416), 
	.d(txdp), 
	.c(n_885), 
	.b(n415), 
	.a(n479));
   ao12m03 U445 (.o(n415), 
	.c(n_224), 
	.b(phy_tx_mode), 
	.a(n414));
   in01s04 U446 (.o(n414), 
	.a(i_tx_phy_sd_nrzi_o));
   no03m02 U447 (.o(n224), 
	.c(n319), 
	.b(n320), 
	.a(n406));
   na04m03 U448 (.o(n304), 
	.d(i_tx_phy_hold_reg_d_17), 
	.c(n303), 
	.b(i_tx_phy_bit_cnt_2_), 
	.a(n_238));
   oa22m02 U449 (.o(n_361), 
	.d(n406), 
	.c(n407), 
	.b(FE_PSN5_n247), 
	.a(n409));
   in01s04 U450 (.o(n409), 
	.a(i_tx_phy_sd_bs_o));
   oa22s04 U451 (.o(n_388), 
	.d(n253), 
	.c(n407), 
	.b(n360), 
	.a(n254));
   na02m02 U452 (.o(n_401), 
	.b(n258), 
	.a(n259));
   na03m03 U453 (.o(n259), 
	.c(n255), 
	.b(n307), 
	.a(i_tx_phy_one_cnt_0_));
   na03m03 U454 (.o(n258), 
	.c(n257), 
	.b(i_tx_phy_one_cnt_1_), 
	.a(n413));
   oa12s04 U455 (.o(n257), 
	.c(i_tx_phy_one_cnt_2_), 
	.b(n256), 
	.a(n_885));
   oa22m03 U456 (.o(n_378), 
	.d(n406), 
	.c(n308), 
	.b(n360), 
	.a(n309));
   no02s03 U457 (.o(n_387), 
	.b(n264), 
	.a(n485));
   in01s02 U458 (.o(n263), 
	.a(n225));
   oa12m02 U459 (.o(n53), 
	.c(n273), 
	.b(n289), 
	.a(n272));
   in01s04 U460 (.o(n273), 
	.a(i_tx_phy_hold_reg_9));
   na02s03 U461 (.o(n272), 
	.b(DataOut_i_6_), 
	.a(n286));
   oa12m02 U462 (.o(n52), 
	.c(n269), 
	.b(n289), 
	.a(n238));
   in01s04 U463 (.o(n269), 
	.a(i_tx_phy_hold_reg_8));
   in01s02 U464 (.o(n238), 
	.a(n235));
   no02m02 U465 (.o(n235), 
	.b(n237), 
	.a(n236));
   ao12m02 U466 (.o(n_415), 
	.c(n318), 
	.b(i_tx_phy_bit_cnt_2_), 
	.a(n317));
   no02f01 U467 (.o(n271), 
	.b(n270), 
	.a(i_tx_phy_bit_cnt_1_));
   no03m03 U468 (.o(n_395), 
	.c(n260), 
	.b(n261), 
	.a(n270));
   oa12s04 U469 (.o(n260), 
	.c(i_tx_phy_bit_cnt_0_), 
	.b(n_885), 
	.a(n413));
   no03s06 U470 (.o(n261), 
	.c(n311), 
	.b(i_tx_phy_bit_cnt_0_), 
	.a(i_tx_phy_one_cnt_0_));
   oa12m04 U471 (.o(n327), 
	.c(i_tx_phy_append_eop_sync4), 
	.b(FE_OFCN3_n467), 
	.a(n408));
   in01s03 U472 (.o(n408), 
	.a(n432));
   in01m02 U473 (.o(n_316), 
	.a(n326));
   in01m02 U474 (.o(n_317), 
	.a(n325));
   ao12m02 U475 (.o(n487), 
	.c(i_tx_phy_data_done), 
	.b(n484), 
	.a(n483));
   no02s03 U476 (.o(n484), 
	.b(n_929), 
	.a(n482));
   na02f01 U477 (.o(n_992), 
	.b(n480), 
	.a(n481));
   oa22s04 U478 (.o(n480), 
	.d(i_rx_phy_shift_en), 
	.c(n_885), 
	.b(RxActive_o), 
	.a(n479));
   ao12m04 U479 (.o(n476), 
	.c(n499), 
	.b(n494), 
	.a(i_rx_phy_rxdp_s));
   no02m02 U480 (.o(n4), 
	.b(n424), 
	.a(n488));
   no02s03 U481 (.o(n424), 
	.b(i_rx_phy_se0_s), 
	.a(n_885));
   oa22s04 U482 (.o(n_203), 
	.d(n_885), 
	.c(n431), 
	.b(n228), 
	.a(n430));
   in01s04 U483 (.o(n_309), 
	.a(n421));
   no02s03 U484 (.o(n421), 
	.b(i_rx_phy_rxdp_s_r_reg_Q), 
	.a(n30));
   in01s04 U485 (.o(n30), 
	.a(n420));
   na02s03 U486 (.o(n420), 
	.b(i_rx_phy_rxdp_s0), 
	.a(LineState_o_0_));
   in01s04 U487 (.o(n_310), 
	.a(n423));
   no02s03 U488 (.o(n423), 
	.b(i_rx_phy_rxdn_s_r_reg_Q), 
	.a(n26));
   in01s04 U489 (.o(n26), 
	.a(n422));
   oa12s04 U490 (.o(n_229), 
	.c(n249), 
	.b(n250), 
	.a(n248));
   in01s04 U491 (.o(n250), 
	.a(i_rx_phy_rxd_s1_reg_Q));
   in01s04 U492 (.o(n249), 
	.a(i_rx_phy_rxd_s0));
   no02s03 U493 (.o(n222), 
	.b(n460), 
	.a(n461));
   in01s04 U494 (.o(n461), 
	.a(i_rx_phy_rx_valid1));
   na02f01 U495 (.o(n507), 
	.b(n458), 
	.a(n459));
   na03m03 U496 (.o(n458), 
	.c(n460), 
	.b(i_rx_phy_rx_valid1), 
	.a(rst));
   na03m02 U497 (.o(n465), 
	.c(n464), 
	.b(RxActive_o), 
	.a(rst));
   na02s03 U498 (.o(n464), 
	.b(i_rx_phy_rx_valid_r), 
	.a(n510));
   oa12m02 U499 (.o(n_962), 
	.c(n439), 
	.b(n448), 
	.a(n438));
   na02s03 U500 (.o(n447), 
	.b(i_rx_phy_one_cnt_1_), 
	.a(n443));
   no03m03 U501 (.o(n440), 
	.c(n489), 
	.b(n228), 
	.a(i_rx_phy_one_cnt_0_));
   oa12s04 U502 (.o(n374), 
	.c(n372), 
	.b(n373), 
	.a(n371));
   na02f02 U503 (.o(n344), 
	.b(n342), 
	.a(n343));
   na02f04 U504 (.o(n460), 
	.b(n_885), 
	.a(n450));
   na03f04 U505 (.o(n450), 
	.c(n449), 
	.b(i_rx_phy_one_cnt_1_), 
	.a(i_rx_phy_one_cnt_2_));
   oa12f06 U506 (.o(n367), 
	.c(i_rx_phy_dpll_state_0_), 
	.b(n372), 
	.a(rst));
   na02f02 U507 (.o(n284), 
	.b(DataOut_i_0_), 
	.a(n286));
   na02f02 U508 (.o(n287), 
	.b(DataOut_i_1_), 
	.a(n286));
   na02f02 U509 (.o(n282), 
	.b(DataOut_i_2_), 
	.a(n286));
   na02f02 U510 (.o(n280), 
	.b(DataOut_i_3_), 
	.a(n286));
   na02f02 U511 (.o(n274), 
	.b(DataOut_i_4_), 
	.a(n286));
   na02s02 U512 (.o(n448), 
	.b(n441), 
	.a(n445));
   no02s02 U513 (.o(n477), 
	.b(n496), 
	.a(n498));
   na02m02 U514 (.o(n241), 
	.b(n242), 
	.a(n441));
   ao12m02 U515 (.o(n377), 
	.c(n375), 
	.b(n376), 
	.a(n374));
   no02m02 U516 (.o(n396), 
	.b(n405), 
	.a(n381));
   in01m01 U517 (.o(n278), 
	.a(n358));
   na03m02 U518 (.o(n481), 
	.c(n476), 
	.b(n477), 
	.a(n478));
   no03m02 U519 (.o(n302), 
	.c(n299), 
	.b(n300), 
	.a(n301));
   na02s02 U520 (.o(n308), 
	.b(n307), 
	.a(n309));
   no02m02 U521 (.o(n455), 
	.b(n453), 
	.a(n451));
   in01m01 U522 (.o(n381), 
	.a(n384));
   in01m02 U523 (.o(n434), 
	.a(n243));
   in01s01 U524 (.o(n393), 
	.a(n392));
   in01s01 U525 (.o(n399), 
	.a(n404));
   na02m02 U526 (.o(n265), 
	.b(n268), 
	.a(n267));
   na02s02 U527 (.o(n277), 
	.b(TxValid_i), 
	.a(n245));
   in01m01 U528 (.o(n382), 
	.a(n398));
   in01s01 U529 (.o(g1897_u0_o), 
	.a(n229));
   in01m02 U530 (.o(n452), 
	.a(n231));
   no02m02 U531 (.o(n355), 
	.b(n245), 
	.a(n349));
   na02m02 U532 (.o(n338), 
	.b(rst), 
	.a(n335));
   na02m02 U533 (.o(n231), 
	.b(n460), 
	.a(n232));
   na03m02 U534 (.o(n466), 
	.c(n463), 
	.b(n477), 
	.a(n478));
   no03m02 U535 (.o(n401), 
	.c(n403), 
	.b(n404), 
	.a(n397));
   no02s01 U536 (.o(n229), 
	.b(n460), 
	.a(n230));
   na02m02 U537 (.o(n429), 
	.b(n472), 
	.a(n494));
   in01s02 U538 (.o(n485), 
	.a(n345));
   oa22m02 U539 (.o(n335), 
	.d(n332), 
	.c(n351), 
	.b(n333), 
	.a(n334));
   in01s01 U540 (.o(n446), 
	.a(n444));
   ao12m02 U541 (.o(n368), 
	.c(n370), 
	.b(n375), 
	.a(n367));
   na02m02 U542 (.o(n390), 
	.b(n389), 
	.a(n391));
   in01s02 U543 (.o(n247), 
	.a(n432));
   in01s01 U544 (.o(RxError_o), 
	.a(n506));
   no02s04 U545 (.o(n307), 
	.b(n362), 
	.a(n251));
   na02s01 U546 (.o(n512), 
	.b(TxValid_i), 
	.a(rst));
   na02s01 U547 (.o(n486), 
	.b(TxValid_i), 
	.a(rst));
   in01s01 U548 (.o(n266), 
	.a(TxValid_i));
   in01f10 U549 (.o(n245), 
	.a(n_929));
   ao12f02 U550 (.o(n300), 
	.c(n310), 
	.b(i_tx_phy_hold_reg_d_reg_5__Q), 
	.a(n296));
   na02f08 U551 (.o(n251), 
	.b(i_tx_phy_sd_raw_o), 
	.a(n_885));
   no02f06 U552 (.o(n432), 
	.b(n_885), 
	.a(FE_OFCN3_n467));
   ao12f02 U553 (.o(n264), 
	.c(n263), 
	.b(i_tx_phy_data_done), 
	.a(n483));
   ao12f02 U554 (.o(n253), 
	.c(n255), 
	.b(i_tx_phy_one_cnt_2_), 
	.a(n252));
   no03f10 U555 (.o(n301), 
	.c(i_tx_phy_hold_reg_d_14), 
	.b(i_tx_phy_bit_cnt_0_), 
	.a(i_tx_phy_bit_cnt_1_));
   oa12f02 U556 (.o(n505), 
	.c(i_rx_phy_rxdp_s), 
	.b(n499), 
	.a(n495));
   ao12f02 U557 (.o(n495), 
	.c(n498), 
	.b(n494), 
	.a(i_rx_phy_fs_state_0_));
   oa12f02 U558 (.o(n412), 
	.c(n411), 
	.b(i_tx_phy_sd_nrzi_o), 
	.a(n410));
   na02f02 U559 (.o(n410), 
	.b(n411), 
	.a(i_tx_phy_sd_nrzi_o));
   ao12f02 U560 (.o(n331), 
	.c(n345), 
	.b(n483), 
	.a(n330));
   in01f10 U561 (.o(n482), 
	.a(i_tx_phy_state_1_));
   na02f02 U562 (.o(n242), 
	.b(n246), 
	.a(i_rx_phy_bit_cnt_2_));
   oa22f02 U563 (.o(n437), 
	.d(i_rx_phy_one_cnt_1_), 
	.c(n244), 
	.b(n445), 
	.a(n436));
   no02f02 U564 (.o(n402), 
	.b(n396), 
	.a(rst_cnt_4_));
   oa22f02 U565 (.o(n_523), 
	.d(n474), 
	.c(n428), 
	.b(n429), 
	.a(n503));
   no02f04 U566 (.o(n286), 
	.b(n237), 
	.a(n276));
   na03f02 U567 (.o(n459), 
	.c(i_rx_phy_bit_cnt_2_), 
	.b(n246), 
	.a(rst));
   oa12f02 U568 (.o(n443), 
	.c(i_rx_phy_one_cnt_2_), 
	.b(n489), 
	.a(n_885));
   oa22f02 U569 (.o(n470), 
	.d(n_796), 
	.c(n498), 
	.b(n425), 
	.a(n469));
   ao12f02 U570 (.o(n324), 
	.c(n323), 
	.b(i_tx_phy_append_eop), 
	.a(n322));
   no03f02 U571 (.o(n353), 
	.c(n486), 
	.b(n352), 
	.a(n_929));
   oa12f02 U572 (.o(n330), 
	.c(n_224), 
	.b(n333), 
	.a(n329));
   oa22f02 U573 (.o(n418), 
	.d(phy_tx_mode), 
	.c(n227), 
	.b(i_tx_phy_sd_nrzi_o), 
	.a(n417));
   oa12f02 U574 (.o(n_449), 
	.c(n375), 
	.b(n369), 
	.a(n368));
   ao12f02 U575 (.o(n_925), 
	.c(n504), 
	.b(n505), 
	.a(n503));
   ao12f02 U576 (.o(n_428), 
	.c(n397), 
	.b(n387), 
	.a(n386));
   oa12f02 U577 (.o(n386), 
	.c(n397), 
	.b(n387), 
	.a(n398));
   ao12f02 U578 (.o(n294), 
	.c(n292), 
	.b(n293), 
	.a(n291));
   no03f02 U579 (.o(n252), 
	.c(n309), 
	.b(n255), 
	.a(i_tx_phy_one_cnt_2_));
   na02f02 U580 (.o(n349), 
	.b(n336), 
	.a(n337));
   oa12f02 U581 (.o(n395), 
	.c(n391), 
	.b(rst_cnt_3_), 
	.a(n390));
   oa12f02 U582 (.o(n299), 
	.c(i_tx_phy_hold_reg_d_reg_6__Q), 
	.b(n310), 
	.a(n298));
   in01f02 U583 (.o(n_364), 
	.a(n419));
   ao22f02 U584 (.o(n419), 
	.d(n432), 
	.c(txdn), 
	.b(FE_PSN8_n243), 
	.a(n418));
   oa22f02 U585 (.o(n306), 
	.d(n294), 
	.c(n295), 
	.b(i_tx_phy_hold_reg_d_reg_3__Q), 
	.a(n319));
   ao12f02 U586 (.o(n346), 
	.c(n482), 
	.b(n345), 
	.a(n344));
   ao12f02 U587 (.o(n357), 
	.c(n347), 
	.b(n348), 
	.a(n346));
   no04f02 U588 (.o(n220), 
	.d(n492), 
	.c(n450), 
	.b(n489), 
	.a(n490));
   no03f02 U589 (.o(n_367), 
	.c(n382), 
	.b(n383), 
	.a(n396));
   na02f01 U590 (.o(n509), 
	.b(n465), 
	.a(n466));
   na02f01 U591 (.o(n_432), 
	.b(n349), 
	.a(n338));
   na02f02 U592 (.o(n378), 
	.b(rst_cnt_0_), 
	.a(n_885));
   na03f02 U593 (.o(n454), 
	.c(n_353), 
	.b(i_rx_phy_bit_cnt_0_), 
	.a(n_885));
   no02f02 U594 (.o(n_417), 
	.b(n394), 
	.a(n395));
   no03f02 U595 (.o(n356), 
	.c(n353), 
	.b(n354), 
	.a(n355));
   na03f02 U596 (.o(n291), 
	.c(n320), 
	.b(n310), 
	.a(n_238));
   no02f02 U597 (.o(n_409), 
	.b(n324), 
	.a(FE_OFCN3_n467));
   no03f02 U598 (.o(n322), 
	.c(n225), 
	.b(n485), 
	.a(i_tx_phy_data_done));
   no02f02 U599 (.o(n223), 
	.b(n331), 
	.a(FE_OFCN3_n467));
   no02f02 U600 (.o(n_414), 
	.b(n240), 
	.a(n241));
   na02f02 U601 (.o(n_459), 
	.b(n356), 
	.a(n357));
   na03f02 U602 (.o(n_276), 
	.c(n412), 
	.b(i_tx_phy_txoe_r1), 
	.a(n413));
   no02f02 U603 (.o(n411), 
	.b(i_tx_phy_sd_bs_o), 
	.a(n479));
   no03f02 U604 (.o(n_392), 
	.c(n485), 
	.b(n486), 
	.a(n487));
   no03f02 U605 (.o(n_394), 
	.c(n362), 
	.b(n318), 
	.a(n271));
   no03f02 U606 (.o(n270), 
	.c(n296), 
	.b(n228), 
	.a(n406));
   no02f02 U607 (.o(n262), 
	.b(n_929), 
	.a(i_tx_phy_state_2_));
   no03f02 U608 (.o(n219), 
	.c(n400), 
	.b(n401), 
	.a(n402));
   na03f02 U609 (.o(n473), 
	.c(n470), 
	.b(n471), 
	.a(n472));
   na03f02 U610 (.o(n508), 
	.c(n304), 
	.b(n305), 
	.a(n306));
   no03f02 U611 (.o(n_407), 
	.c(n457), 
	.b(n455), 
	.a(n452));
   na02f01 U612 (.o(n369), 
	.b(n511), 
	.a(n372));
   ao12f01 U613 (.o(n462), 
	.c(n228), 
	.b(i_rx_phy_rx_valid_r), 
	.a(RxValid_o));
   ao22f01 U614 (.o(n325), 
	.d(i_tx_phy_append_eop_sync1), 
	.c(n432), 
	.b(n243), 
	.a(i_tx_phy_append_eop));
   ao22f01 U615 (.o(n326), 
	.d(i_tx_phy_append_eop_sync1), 
	.c(FE_PSN8_n243), 
	.b(i_tx_phy_append_eop_sync2), 
	.a(n432));
   na02f01 U616 (.o(n_507), 
	.b(n278), 
	.a(n279));
   oa22f01 U617 (.o(n279), 
	.d(i_tx_phy_hold_reg_10), 
	.c(i_tx_phy_ld_data_reg_Q), 
	.b(DataOut_i_7_), 
	.a(n276));
   oa22f01 U618 (.o(n_288), 
	.d(n227), 
	.c(n434), 
	.b(n247), 
	.a(n321));
   oa12f01 U619 (.o(n_365), 
	.c(n434), 
	.b(n435), 
	.a(n433));
   oa12f01 U620 (.o(n_319), 
	.c(n361), 
	.b(n434), 
	.a(n360));
   in01f01 U621 (.o(n323), 
	.a(i_tx_phy_append_eop_sync2));
   in01f01 U622 (.o(n_338), 
	.a(n328));
   oa12f01 U623 (.o(n394), 
	.c(n393), 
	.b(rst_cnt_3_), 
	.a(n398));
   in01f01 U624 (.o(n288), 
	.a(i_tx_phy_hold_reg_4));
   na02f01 U625 (.o(n334), 
	.b(n_929), 
	.a(n_224));
   oa12f01 U626 (.o(n50), 
	.c(n281), 
	.b(n289), 
	.a(n280));
   in01f01 U627 (.o(n281), 
	.a(i_tx_phy_hold_reg_6));
   oa12f01 U628 (.o(n47), 
	.c(n285), 
	.b(n289), 
	.a(n284));
   in01f01 U629 (.o(n285), 
	.a(i_tx_phy_hold_reg));
   oa12f01 U630 (.o(n49), 
	.c(n283), 
	.b(n289), 
	.a(n282));
   in01f01 U631 (.o(n283), 
	.a(i_tx_phy_hold_reg_5));
   oa12f01 U632 (.o(n51), 
	.c(n275), 
	.b(n289), 
	.a(n274));
   in01f01 U633 (.o(n275), 
	.a(i_tx_phy_hold_reg_7));
   no02f01 U634 (.o(n240), 
	.b(n246), 
	.a(i_rx_phy_bit_cnt_2_));
endmodule

